
* [Hi] Hello -> END #hey

/*
INK_TEST_STORY_START
[
	{"TEST_ERROR_EQUAL": 0},
	{"TEST_WARNING_EQUAL": 0},
	{"EXECUTE_STORY_CONTINUE": "-1"},
    {"EXECUTE_STORY_CHOICE": 0},
    {"EXECUTE_STORY_CONTINUE": "Hello"},
    {"TEST_CURRENT_TAGS": ["hey"]}
]
INK_TEST_END
*/