*   [Option]
    Text
    
/*
INK_TEST_STORY_START
[
	{"TEST_ERROR_EQUAL": 0},
	{"TEST_WARNING_EQUAL": 0},
	{"EXECUTE_STORY_CONTINUE": "-1"},
	{"TEST_CHOICE_COUNT": 1},
	{"TEST_CHOICE_TEXT": [0, "Option"]},
	{"EXECUTE_STORY_CHOICE": 0},
	{"EXECUTE_STORY_CONTINUE": "Text\n"}
]
INK_TEST_END
*/